package props

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

type Config struct {
	MOTD       string
	MaxPlayers int
	Port       int
	Difficulty string
	Gamemode   string
	Whitelist  bool
	OnlineMode bool
}

func Default() Config {
	return Config{
		MOTD:       "Server created with Deblock",
		MaxPlayers: 20,
		Port:       25565,
		Difficulty: "easy",
		Gamemode:   "survival",
		Whitelist:  false,
		OnlineMode: true,
	}
}

func Write(path string, c Config) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	fmt.Fprintln(w, "# Generated by Deblock installation wizard - you can also edit it manually")
	fmt.Fprintf(w, "motd=%s\n", c.MOTD)
	fmt.Fprintf(w, "max-players=%d\n", c.MaxPlayers)
	fmt.Fprintf(w, "server-port=%d\n", c.Port)
	fmt.Fprintf(w, "difficulty=%s\n", c.Difficulty)
	fmt.Fprintf(w, "gamemode=%s\n", c.Gamemode)
	fmt.Fprintf(w, "white-list=%t\n", c.Whitelist)
	fmt.Fprintf(w, "online-mode=%t\n", c.OnlineMode)
	fmt.Fprintln(w, "enable-command-block=false")
	fmt.Fprintln(w, "view-distance=10")
	return w.Flush()
}

func Read(path string) (Config, bool) {
	c := Default()
	f, err := os.Open(path)
	if err != nil {
		return c, false
	}
	defer f.Close()

	values := map[string]string{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		values[parts[0]] = parts[1]
	}

	if v, ok := values["motd"]; ok {
		c.MOTD = v
	}
	if v, ok := values["max-players"]; ok {
		if n, err := strconv.Atoi(v); err == nil {
			c.MaxPlayers = n
		}
	}
	if v, ok := values["server-port"]; ok {
		if n, err := strconv.Atoi(v); err == nil {
			c.Port = n
		}
	}
	if v, ok := values["difficulty"]; ok {
		c.Difficulty = v
	}
	if v, ok := values["gamemode"]; ok {
		c.Gamemode = v
	}
	if v, ok := values["white-list"]; ok {
		c.Whitelist = v == "true"
	}
	if v, ok := values["online-mode"]; ok {
		c.OnlineMode = v == "true"
	}
	return c, true
}
